import { createApp } from 'vue';
import VueToast from 'vue-toast-notification';
import 'vue-toast-notification/dist/theme-sugar.css';
import AppCostumeSelect from './components/AppCostumeSelect.vue';
import App from './App.vue';
import router from './router';
import store from './store';
import VeeValidatePlugin from './includes/validation';
import './assets/js/lib/bootstrap.min';
// import tikaUtils from './assets/js/custom';
import './assets/css/lib/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import './assets/css/iransans.css';
import './assets/css/style.css';
import './registerServiceWorker';

const vm = createApp(App);
vm.component('AppSelect', AppCostumeSelect);
vm.config.productionTip = false;
vm.use(VueToast);
vm.use(VeeValidatePlugin);
vm.use(store);
vm.use(router);
vm.mount('#app');
